import 'localization_service.dart';

enum TKeys {
  settings,
  language,
  common,
  enable_not,
  sign_out,
  serial_no_c,
  serial_no,
  brand_c,
  brand,
  code_C,
  code,
  add_bike,
  all_of_the_bikes,
  r_u_sure_del,
  yes,
  cancel,
  numb_of_avail_bikes_c,
  numb_of_rpr_bikes_c,
  bike_c,
  my_bike,
  bike_code_c_n,
  rmn_time_n,
  gv_bck_bike,
  acnt,
  issued,
  n_rtrn_n,
  lock,
  numb_of_total_bikes,
  bike_avail,
  numb_of_avail_bikes,
  repair,
  numb_of_rpr_bikes,
  circulation,
  numb_of_circ_bikes,
  take_req,
  numb_of_take_req_bikes_c,
  return_req,
  numb_of_return_req_bikes_c,
  total,
  reqs,
  code_c_b,
  b_serial_n_c_b,
  b_account_c_b,
  sel_op,
  del_bike,
  rpr_bike,
  crc_bike,
  b_owner_c_b,
  bike_c_b,
  error,
  alrdy_req,
  history,
  return_s,
  home,
  take_bike,
  entr_ur_mail,
  pass,
  dnt_accnt,
  sgn_up,
  rst_pass,
  frgt_pass,
  login_big,
  login,
  entr_ur_pass_again,
  bike_recordok_record,
  ok_record,
  alr_accnt,
  bike_code,
  bikepage
}

//TKeys.hello
extension TKeysExtention on TKeys {
  String get _string => toString().split('.')[1];

  String translate(context) {
    return LocalizationService.of(context).translate(_string) ?? '';
  }
}
